version: '3.7'
name: ${COMPOSE_PROJECT_NAME}
services:
    webserver:
        container_name: ${COMPOSE_PROJECT_NAME}-webserver
        image: 'nginx:alpine'
        working_dir: /var/www/src/
        volumes:
            - ../:/var/www/
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        depends_on:
            - app
        env_file:
            - ".env"
    app:
        build:
            context: ./php/.
            args:
                APP_ENV: ${APP_ENV}
        container_name: ${COMPOSE_PROJECT_NAME}-app
        working_dir: /var/www/src/
        volumes:
            - ../:/var/www/
            - './php/php.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        depends_on:
            - database
        env_file:
            - ".env"
    database:
        container_name: ${COMPOSE_PROJECT_NAME}-database
        image: mysql:latest
        ports:
            - ${DATABASE_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_DATABASE}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - database:/var/lib/mysql
        env_file:
            - ".env"
volumes:
    database: